"""remove profile img from profile img

Revision ID: 077f03ef435a
Revises: b9b7638e3804
Create Date: 2025-12-06 19:16:53.472875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077f03ef435a'
down_revision: Union[str, Sequence[str], None] = 'b9b7638e3804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_img', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
