"""Add provider IDS to subscription table

Revision ID: 17d57bf7495f
Revises: 799ac1c3c766
Create Date: 2025-12-01 11:12:41.167455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d57bf7495f'
down_revision: Union[str, Sequence[str], None] = '799ac1c3c766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('provider', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('provider_subscription_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('provider_customer_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['provider_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'provider_customer_id')
    op.drop_column('subscriptions', 'provider_subscription_id')
    op.drop_column('subscriptions', 'provider')
    # ### end Alembic commands ###
