"""Add canceled_at to subscripe

Revision ID: 498c284674c8
Revises: 17d57bf7495f
Create Date: 2025-12-02 09:46:19.703937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498c284674c8'
down_revision: Union[str, Sequence[str], None] = '17d57bf7495f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'canceled_at')
    # ### end Alembic commands ###
