"""update payments table

Revision ID: 4d2351950575
Revises: 901c3892e78d
Create Date: 2025-12-05 20:50:17.510430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2351950575'
down_revision: Union[str, Sequence[str], None] = '901c3892e78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_invoice_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('provider_charge_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_constraint(op.f('uq_provider_payment_id'), 'payments', type_='unique')
    op.create_index(op.f('ix_payments_provider_charge_id'), 'payments', ['provider_charge_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_invoice_id'), 'payments', ['provider_invoice_id'], unique=False)
    op.create_unique_constraint('uq_provider_charge_id', 'payments', ['provider', 'provider_charge_id'])
    op.create_unique_constraint('uq_provider_invoice_id', 'payments', ['provider', 'provider_invoice_id'])
    op.drop_column('payments', 'provider_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_payment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_provider_invoice_id', 'payments', type_='unique')
    op.drop_constraint('uq_provider_charge_id', 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_provider_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_charge_id'), table_name='payments')
    op.create_unique_constraint(op.f('uq_provider_payment_id'), 'payments', ['provider', 'provider_payment_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.drop_column('payments', 'provider_charge_id')
    op.drop_column('payments', 'provider_invoice_id')
    # ### end Alembic commands ###
