"""Add Stripe IDs to Plan

Revision ID: 7717980b70c7
Revises: 2da523c120f7
Create Date: 2025-11-30 18:34:26.636243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7717980b70c7'
down_revision: Union[str, Sequence[str], None] = '2da523c120f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('stripe_product_id', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('stripe_price_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'stripe_price_id')
    op.drop_column('plans', 'stripe_product_id')
    # ### end Alembic commands ###
