"""update payments table remove charge id

Revision ID: b9b7638e3804
Revises: 4d2351950575
Create Date: 2025-12-05 21:01:17.019380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b7638e3804'
down_revision: Union[str, Sequence[str], None] = '4d2351950575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_provider_charge_id'), table_name='payments')
    op.drop_constraint(op.f('uq_provider_charge_id'), 'payments', type_='unique')
    op.drop_column('payments', 'provider_charge_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_charge_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_provider_charge_id'), 'payments', ['provider', 'provider_charge_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_payments_provider_charge_id'), 'payments', ['provider_charge_id'], unique=False)
    # ### end Alembic commands ###
