"""add plan tier to plans

Revision ID: d511d819de27
Revises: e703423eb0a3
Create Date: 2025-12-05 20:19:57.009296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd511d819de27'
down_revision: Union[str, Sequence[str], None] = 'e703423eb0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    def upgrade() -> None:
        op.add_column(
            "plans",
            sa.Column(
                "tier",
                sa.Enum("FREE", "PRO", "VIP", name="plantier"),
                nullable=False,
                server_default="FREE",  # may or may not be generated automatically
            ),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "tier")
    sa.Enum(name="plantier").drop(op.get_bind())
    # ### end Alembic commands ###
