"""add pending to sub status

Revision ID: e703423eb0a3
Revises: df4edd4ef14b
Create Date: 2025-12-03 19:41:06.008939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e703423eb0a3'
down_revision: Union[str, Sequence[str], None] = 'df4edd4ef14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'pending';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
